### ISSUE TITLE
Facing hard time to implement Android swagger client.

### ISSUE THREAD

**Issue by boygaggoo** [umranium/swagger-codegen#1]
##### how i can implement apiInvoker lib after generating with jar file.Thanks

Any new sample with new API Source. 

Whats the point sir if you did not put the sample apps how to use generated code.

**Comment by umranium** [comment]
Hi,

Thanks for your comment.

I added some examples on how to use the specific features added in this repository into the [release documentation here](https://github.com/umranium/swagger-codegen/releases/tag/v2.2.2-additions).

If you are after examples of how to use swagger-codegen in general, please raise this in the [parent repository here](https://github.com/swagger-api/swagger-codegen).

Cheers!
